# Generated by Django 3.1.5 on 2021-01-24 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_project',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_project',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
