# Generated by Django 3.1.5 on 2021-01-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210124_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_project',
            name='text',
            field=models.TextField(default='1999,1,1', max_length=400),
            preserve_default=False,
        ),
    ]
